export default {
  INITIALIZE_KAKURO: "INITIALIZE_KAKURO",
  CHANGE_KAKURO_CELL: "CHANGE_KAKURO_CELL",
  SAVE_KAKURO: "SAVE_KAKURO",
  INITIALIZE_SPIDERS: "INITIALIZE_SPIDERS",
  UPDATE_SPIDER_POSITION: "UPDATE_SPIDER_POSITION",
  UPDATE_SPIDER: "UPDATE_SPIDER"
};
