export default {
  INITIALIZE_KAKURO: "INITIALIZE_KAKURO",
  RESET_KAKURO: "RESET_KAKURO",
  CHANGE_KAKURO_CELL: "CHANGE_KAKURO_CELL",
  SAVE_KAKURO: "SAVE_KAKURO",
  SOLVE_KAKURO: "SOLVE_KAKURO",
  UPDATE_KAKURO_SOLUTION: "UPDATE_KAKURO_SOLUTION",
  INITIALIZE_SPIDERS: "INITIALIZE_SPIDERS",
  UPDATE_SPIDER_POSITION: "UPDATE_SPIDER_POSITION",
  UPDATE_SPIDER: "UPDATE_SPIDER",
  ADD_TOAST: "CREATE_TOAST",
  REMOVE_TOAST: "REMOVE_TOAST"
};
